on: push
name: Deploy Apps
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v1
        with:
          node-version: "16.16.0"

      - name: Install dependencies
        run: npm install

      - name: Run project
        run: npm start

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.playfala.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/apps/barbershop/be-barbershop/
